# Generated by Django 4.2.13 on 2024-05-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='q',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='p_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_text',
            new_name='question_text',
        ),
    ]
